### ISSUE TITLE
current workflow failed on AMD MI300X with rocm 6.2 and pytorch 2.4

### ISSUE THREAD

**Issue by gfursin** [mlcommons/cm4mlperf-inference#48]
Hi,
I finally found some time to try the SCC'24 tutorial to run SDXL on AMD MI300X - the workflow resolved all dependencies but failed in loadgen. I attached the CM logs and deps.
Did you see such error - any ideas what is happening?
Which PyTorch version did you try?
Thank you,
Grigori
[error-rocm.txt](https://github.com/user-attachments/files/17391003/error-rocm.txt)
[error-rocm-deps.txt](https://github.com/user-attachments/files/17391004/error-rocm-deps.txt)

Extra ref: https://github.com/mlcommons/cm4mlops/issues/300

**Comment by arjunsuresh** [comment]
I'm not sure of the exact torch version used as it was done by the AMD team. But the below error looks like a HIP driver installation issue - the driver installation and detection for AMD GPUs are not done in CM like we do for Nvidia GPUs as we don't have a test system.

```
 File "/persistent_storage/gfursin/cm/lib/python3.10/site-packages/torch/cuda/__init__.py", line 319, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
```

**Comment by gfursin** [comment]
Sure. We will investigate it further internally. Thanks!

**Comment by gfursin** [comment]
Fixed it - AMD ROCm drivers were not installed properly ;) .
